Implement redux/create-module
TechnologyAdvice/ta-react pull request #5
Opened 2016-11-10 22:33 UTC by davezuko

2016-11-10 22:49 UTC, levithomason requested changes

2016-11-10 22:49 UTC, levithomason commented on src/redux/create-module.js
> +const mapKeys = (fn, obj) => Object.keys(obj)
Can we pull this into a `lib` folder for reuse/testing?

2016-11-11 14:31 UTC, davezuko commented on src/redux/create-module.js
> +const mapKeys = (fn, obj) => Object.keys(obj)
For sure, good idea. Will update.

2016-11-11 22:51 UTC, levithomason approved these changes

2016-11-11 22:52 UTC, levithomason commented
Moved mapKeys to `lib` and added `createModule` to `redux/index.js`.

2016-11-11 22:52 UTC, merged